### ISSUE TITLE
more better burp sounds

### ISSUE THREAD

**Issue by treakiandroid** [no-go/RickApp#2]
Rick and Morty are grate, but you could improve the app with more then this tiny burp sound file, include at least 10 Burp's that are picked randomly including realy long/dirty ones ;)

also a background running notification would be nice and you could check phone status and auto quit on incoming calls.

**Comment by alltagshack** [comment]
1. It is hard to record really 10 different Burp's. I think, 5 different ones are possible to me. And it must be opensource burps - without any paramount or other copyright :-P
2. Checking the phone status and auto quit - this is a good idea.
3. A notification to switch the App on/off - nice feature. I think, I can do it.

**Comment by alltagshack** [comment]
To the second point: I test it on Android 4.4 and 6.0 - The "phone App" has a highter prio to get microphone access. On Android 6.0 the microphone is not blocked on my phone ... I think, there is no need to quit/stop RickApp automaticaly on phone calls :-D

**Comment by alltagshack** [comment]
The 3. point needs more time for testing. It still does not work :-( I think adding more burp's is much more easier.
![alpha-testing-notifycontrol](https://cloud.githubusercontent.com/assets/12084008/21325168/338707ce-c625-11e6-9906-751395dcda64.jpg)

**Comment by alltagshack** [comment]
Feature 1 and 3 are added. The second one is less important :-D I hope, the the burp's are "good" for you.

**Comment by treakiandroid** [comment]
very grate, thanks a lot!!!
